"""Initial migration

Revision ID: 32a84cba3ceb
Revises: 
Create Date: 2026-08-22 15:04:55.204606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a84cba3ceb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('equipment_needed', sa.Boolean(), nullable=False),
    sa.CheckConstraint("category IN ('cardio', 'strength', 'flexibility', 'balance')", name='exercise_valid_category'),
    sa.CheckConstraint('length(trim(name)) > 0', name='exercise_name_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('duration_minutes > 0', name='workout_positive_duration'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name='workout_exercise_non_negative_duration'),
    sa.CheckConstraint('reps IS NULL OR reps >= 0', name='workout_exercise_non_negative_reps'),
    sa.CheckConstraint('sets IS NULL OR sets >= 0', name='workout_exercise_non_negative_sets'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('workouts')
    op.drop_table('exercises')
    # ### end Alembic commands ###
